package termbox_go
import (
github_com_nsf_termbox_go "github.com/nsf/termbox-go"
)
var Api map[string]map[string]interface{} = map[string]map[string]interface{}{}
func init() {
if _, ok := Api["github.com/nsf/termbox-go"]; !ok {
   Api["github.com/nsf/termbox-go"] = map[string]interface{}{}
}
if _, ok := Api["github.com/nsf/termbox-go/new"]; !ok {
	Api["github.com/nsf/termbox-go/new"] = map[string]interface{}{}
}
Api["github.com/nsf/termbox-go"]["AttributeToRGB"] = github_com_nsf_termbox_go.AttributeToRGB
Api["github.com/nsf/termbox-go"]["Clear"] = github_com_nsf_termbox_go.Clear
Api["github.com/nsf/termbox-go"]["Close"] = github_com_nsf_termbox_go.Close
Api["github.com/nsf/termbox-go"]["Flush"] = github_com_nsf_termbox_go.Flush
Api["github.com/nsf/termbox-go"]["HideCursor"] = github_com_nsf_termbox_go.HideCursor
Api["github.com/nsf/termbox-go"]["Init"] = github_com_nsf_termbox_go.Init
Api["github.com/nsf/termbox-go"]["Interrupt"] = github_com_nsf_termbox_go.Interrupt
Api["github.com/nsf/termbox-go"]["SetBg"] = github_com_nsf_termbox_go.SetBg
Api["github.com/nsf/termbox-go"]["SetCell"] = github_com_nsf_termbox_go.SetCell
Api["github.com/nsf/termbox-go"]["SetChar"] = github_com_nsf_termbox_go.SetChar
Api["github.com/nsf/termbox-go"]["SetCursor"] = github_com_nsf_termbox_go.SetCursor
Api["github.com/nsf/termbox-go"]["SetFg"] = github_com_nsf_termbox_go.SetFg
Api["github.com/nsf/termbox-go"]["Size"] = github_com_nsf_termbox_go.Size
Api["github.com/nsf/termbox-go"]["Sync"] = github_com_nsf_termbox_go.Sync
Api["github.com/nsf/termbox-go"]["ColorDefault"] = github_com_nsf_termbox_go.ColorDefault
Api["github.com/nsf/termbox-go"]["ColorBlack"] = github_com_nsf_termbox_go.ColorBlack
Api["github.com/nsf/termbox-go"]["ColorRed"] = github_com_nsf_termbox_go.ColorRed
Api["github.com/nsf/termbox-go"]["ColorGreen"] = github_com_nsf_termbox_go.ColorGreen
Api["github.com/nsf/termbox-go"]["ColorYellow"] = github_com_nsf_termbox_go.ColorYellow
Api["github.com/nsf/termbox-go"]["ColorBlue"] = github_com_nsf_termbox_go.ColorBlue
Api["github.com/nsf/termbox-go"]["ColorMagenta"] = github_com_nsf_termbox_go.ColorMagenta
Api["github.com/nsf/termbox-go"]["ColorCyan"] = github_com_nsf_termbox_go.ColorCyan
Api["github.com/nsf/termbox-go"]["ColorWhite"] = github_com_nsf_termbox_go.ColorWhite
Api["github.com/nsf/termbox-go"]["ColorDarkGray"] = github_com_nsf_termbox_go.ColorDarkGray
Api["github.com/nsf/termbox-go"]["ColorLightRed"] = github_com_nsf_termbox_go.ColorLightRed
Api["github.com/nsf/termbox-go"]["ColorLightGreen"] = github_com_nsf_termbox_go.ColorLightGreen
Api["github.com/nsf/termbox-go"]["ColorLightYellow"] = github_com_nsf_termbox_go.ColorLightYellow
Api["github.com/nsf/termbox-go"]["ColorLightBlue"] = github_com_nsf_termbox_go.ColorLightBlue
Api["github.com/nsf/termbox-go"]["ColorLightMagenta"] = github_com_nsf_termbox_go.ColorLightMagenta
Api["github.com/nsf/termbox-go"]["ColorLightCyan"] = github_com_nsf_termbox_go.ColorLightCyan
Api["github.com/nsf/termbox-go"]["ColorLightGray"] = github_com_nsf_termbox_go.ColorLightGray
Api["github.com/nsf/termbox-go"]["AttrBold"] = github_com_nsf_termbox_go.AttrBold
Api["github.com/nsf/termbox-go"]["AttrBlink"] = github_com_nsf_termbox_go.AttrBlink
Api["github.com/nsf/termbox-go"]["AttrHidden"] = github_com_nsf_termbox_go.AttrHidden
Api["github.com/nsf/termbox-go"]["AttrDim"] = github_com_nsf_termbox_go.AttrDim
Api["github.com/nsf/termbox-go"]["AttrUnderline"] = github_com_nsf_termbox_go.AttrUnderline
Api["github.com/nsf/termbox-go"]["AttrCursive"] = github_com_nsf_termbox_go.AttrCursive
Api["github.com/nsf/termbox-go"]["AttrReverse"] = github_com_nsf_termbox_go.AttrReverse
Api["github.com/nsf/termbox-go"]["RGBToAttribute"] = github_com_nsf_termbox_go.RGBToAttribute
Api["github.com/nsf/termbox-go"]["Cell"] = github_com_nsf_termbox_go.Cell{}
Api["github.com/nsf/termbox-go/new"]["Cell"] = func(args ...interface{}) interface{} {
					return new(github_com_nsf_termbox_go.Cell)
}
Api["github.com/nsf/termbox-go"]["CellBuffer"] = github_com_nsf_termbox_go.CellBuffer
Api["github.com/nsf/termbox-go"]["GetCell"] = github_com_nsf_termbox_go.GetCell
Api["github.com/nsf/termbox-go"]["Event"] = github_com_nsf_termbox_go.Event{}
Api["github.com/nsf/termbox-go/new"]["Event"] = func(args ...interface{}) interface{} {
					return new(github_com_nsf_termbox_go.Event)
}
Api["github.com/nsf/termbox-go"]["ParseEvent"] = github_com_nsf_termbox_go.ParseEvent
Api["github.com/nsf/termbox-go"]["PollEvent"] = github_com_nsf_termbox_go.PollEvent
Api["github.com/nsf/termbox-go"]["PollRawEvent"] = github_com_nsf_termbox_go.PollRawEvent
Api["github.com/nsf/termbox-go"]["EventKey"] = github_com_nsf_termbox_go.EventKey
Api["github.com/nsf/termbox-go"]["EventResize"] = github_com_nsf_termbox_go.EventResize
Api["github.com/nsf/termbox-go"]["EventMouse"] = github_com_nsf_termbox_go.EventMouse
Api["github.com/nsf/termbox-go"]["EventError"] = github_com_nsf_termbox_go.EventError
Api["github.com/nsf/termbox-go"]["EventInterrupt"] = github_com_nsf_termbox_go.EventInterrupt
Api["github.com/nsf/termbox-go"]["EventRaw"] = github_com_nsf_termbox_go.EventRaw
Api["github.com/nsf/termbox-go"]["EventNone"] = github_com_nsf_termbox_go.EventNone
Api["github.com/nsf/termbox-go"]["InputEsc"] = github_com_nsf_termbox_go.InputEsc
Api["github.com/nsf/termbox-go"]["InputAlt"] = github_com_nsf_termbox_go.InputAlt
Api["github.com/nsf/termbox-go"]["InputMouse"] = github_com_nsf_termbox_go.InputMouse
Api["github.com/nsf/termbox-go"]["InputCurrent"] = github_com_nsf_termbox_go.InputCurrent
Api["github.com/nsf/termbox-go"]["SetInputMode"] = github_com_nsf_termbox_go.SetInputMode
Api["github.com/nsf/termbox-go"]["KeyF1"] = github_com_nsf_termbox_go.KeyF1
Api["github.com/nsf/termbox-go"]["KeyF2"] = github_com_nsf_termbox_go.KeyF2
Api["github.com/nsf/termbox-go"]["KeyF3"] = github_com_nsf_termbox_go.KeyF3
Api["github.com/nsf/termbox-go"]["KeyF4"] = github_com_nsf_termbox_go.KeyF4
Api["github.com/nsf/termbox-go"]["KeyF5"] = github_com_nsf_termbox_go.KeyF5
Api["github.com/nsf/termbox-go"]["KeyF6"] = github_com_nsf_termbox_go.KeyF6
Api["github.com/nsf/termbox-go"]["KeyF7"] = github_com_nsf_termbox_go.KeyF7
Api["github.com/nsf/termbox-go"]["KeyF8"] = github_com_nsf_termbox_go.KeyF8
Api["github.com/nsf/termbox-go"]["KeyF9"] = github_com_nsf_termbox_go.KeyF9
Api["github.com/nsf/termbox-go"]["KeyF10"] = github_com_nsf_termbox_go.KeyF10
Api["github.com/nsf/termbox-go"]["KeyF11"] = github_com_nsf_termbox_go.KeyF11
Api["github.com/nsf/termbox-go"]["KeyF12"] = github_com_nsf_termbox_go.KeyF12
Api["github.com/nsf/termbox-go"]["KeyInsert"] = github_com_nsf_termbox_go.KeyInsert
Api["github.com/nsf/termbox-go"]["KeyDelete"] = github_com_nsf_termbox_go.KeyDelete
Api["github.com/nsf/termbox-go"]["KeyHome"] = github_com_nsf_termbox_go.KeyHome
Api["github.com/nsf/termbox-go"]["KeyEnd"] = github_com_nsf_termbox_go.KeyEnd
Api["github.com/nsf/termbox-go"]["KeyPgup"] = github_com_nsf_termbox_go.KeyPgup
Api["github.com/nsf/termbox-go"]["KeyPgdn"] = github_com_nsf_termbox_go.KeyPgdn
Api["github.com/nsf/termbox-go"]["KeyArrowUp"] = github_com_nsf_termbox_go.KeyArrowUp
Api["github.com/nsf/termbox-go"]["KeyArrowDown"] = github_com_nsf_termbox_go.KeyArrowDown
Api["github.com/nsf/termbox-go"]["KeyArrowLeft"] = github_com_nsf_termbox_go.KeyArrowLeft
Api["github.com/nsf/termbox-go"]["KeyArrowRight"] = github_com_nsf_termbox_go.KeyArrowRight
Api["github.com/nsf/termbox-go"]["MouseLeft"] = github_com_nsf_termbox_go.MouseLeft
Api["github.com/nsf/termbox-go"]["MouseMiddle"] = github_com_nsf_termbox_go.MouseMiddle
Api["github.com/nsf/termbox-go"]["MouseRight"] = github_com_nsf_termbox_go.MouseRight
Api["github.com/nsf/termbox-go"]["MouseRelease"] = github_com_nsf_termbox_go.MouseRelease
Api["github.com/nsf/termbox-go"]["MouseWheelUp"] = github_com_nsf_termbox_go.MouseWheelUp
Api["github.com/nsf/termbox-go"]["MouseWheelDown"] = github_com_nsf_termbox_go.MouseWheelDown
Api["github.com/nsf/termbox-go"]["KeyCtrlTilde"] = github_com_nsf_termbox_go.KeyCtrlTilde
Api["github.com/nsf/termbox-go"]["KeyCtrl2"] = github_com_nsf_termbox_go.KeyCtrl2
Api["github.com/nsf/termbox-go"]["KeyCtrlSpace"] = github_com_nsf_termbox_go.KeyCtrlSpace
Api["github.com/nsf/termbox-go"]["KeyCtrlA"] = github_com_nsf_termbox_go.KeyCtrlA
Api["github.com/nsf/termbox-go"]["KeyCtrlB"] = github_com_nsf_termbox_go.KeyCtrlB
Api["github.com/nsf/termbox-go"]["KeyCtrlC"] = github_com_nsf_termbox_go.KeyCtrlC
Api["github.com/nsf/termbox-go"]["KeyCtrlD"] = github_com_nsf_termbox_go.KeyCtrlD
Api["github.com/nsf/termbox-go"]["KeyCtrlE"] = github_com_nsf_termbox_go.KeyCtrlE
Api["github.com/nsf/termbox-go"]["KeyCtrlF"] = github_com_nsf_termbox_go.KeyCtrlF
Api["github.com/nsf/termbox-go"]["KeyCtrlG"] = github_com_nsf_termbox_go.KeyCtrlG
Api["github.com/nsf/termbox-go"]["KeyBackspace"] = github_com_nsf_termbox_go.KeyBackspace
Api["github.com/nsf/termbox-go"]["KeyCtrlH"] = github_com_nsf_termbox_go.KeyCtrlH
Api["github.com/nsf/termbox-go"]["KeyTab"] = github_com_nsf_termbox_go.KeyTab
Api["github.com/nsf/termbox-go"]["KeyCtrlI"] = github_com_nsf_termbox_go.KeyCtrlI
Api["github.com/nsf/termbox-go"]["KeyCtrlJ"] = github_com_nsf_termbox_go.KeyCtrlJ
Api["github.com/nsf/termbox-go"]["KeyCtrlK"] = github_com_nsf_termbox_go.KeyCtrlK
Api["github.com/nsf/termbox-go"]["KeyCtrlL"] = github_com_nsf_termbox_go.KeyCtrlL
Api["github.com/nsf/termbox-go"]["KeyEnter"] = github_com_nsf_termbox_go.KeyEnter
Api["github.com/nsf/termbox-go"]["KeyCtrlM"] = github_com_nsf_termbox_go.KeyCtrlM
Api["github.com/nsf/termbox-go"]["KeyCtrlN"] = github_com_nsf_termbox_go.KeyCtrlN
Api["github.com/nsf/termbox-go"]["KeyCtrlO"] = github_com_nsf_termbox_go.KeyCtrlO
Api["github.com/nsf/termbox-go"]["KeyCtrlP"] = github_com_nsf_termbox_go.KeyCtrlP
Api["github.com/nsf/termbox-go"]["KeyCtrlQ"] = github_com_nsf_termbox_go.KeyCtrlQ
Api["github.com/nsf/termbox-go"]["KeyCtrlR"] = github_com_nsf_termbox_go.KeyCtrlR
Api["github.com/nsf/termbox-go"]["KeyCtrlS"] = github_com_nsf_termbox_go.KeyCtrlS
Api["github.com/nsf/termbox-go"]["KeyCtrlT"] = github_com_nsf_termbox_go.KeyCtrlT
Api["github.com/nsf/termbox-go"]["KeyCtrlU"] = github_com_nsf_termbox_go.KeyCtrlU
Api["github.com/nsf/termbox-go"]["KeyCtrlV"] = github_com_nsf_termbox_go.KeyCtrlV
Api["github.com/nsf/termbox-go"]["KeyCtrlW"] = github_com_nsf_termbox_go.KeyCtrlW
Api["github.com/nsf/termbox-go"]["KeyCtrlX"] = github_com_nsf_termbox_go.KeyCtrlX
Api["github.com/nsf/termbox-go"]["KeyCtrlY"] = github_com_nsf_termbox_go.KeyCtrlY
Api["github.com/nsf/termbox-go"]["KeyCtrlZ"] = github_com_nsf_termbox_go.KeyCtrlZ
Api["github.com/nsf/termbox-go"]["KeyEsc"] = github_com_nsf_termbox_go.KeyEsc
Api["github.com/nsf/termbox-go"]["KeyCtrlLsqBracket"] = github_com_nsf_termbox_go.KeyCtrlLsqBracket
Api["github.com/nsf/termbox-go"]["KeyCtrl3"] = github_com_nsf_termbox_go.KeyCtrl3
Api["github.com/nsf/termbox-go"]["KeyCtrl4"] = github_com_nsf_termbox_go.KeyCtrl4
Api["github.com/nsf/termbox-go"]["KeyCtrlBackslash"] = github_com_nsf_termbox_go.KeyCtrlBackslash
Api["github.com/nsf/termbox-go"]["KeyCtrl5"] = github_com_nsf_termbox_go.KeyCtrl5
Api["github.com/nsf/termbox-go"]["KeyCtrlRsqBracket"] = github_com_nsf_termbox_go.KeyCtrlRsqBracket
Api["github.com/nsf/termbox-go"]["KeyCtrl6"] = github_com_nsf_termbox_go.KeyCtrl6
Api["github.com/nsf/termbox-go"]["KeyCtrl7"] = github_com_nsf_termbox_go.KeyCtrl7
Api["github.com/nsf/termbox-go"]["KeyCtrlSlash"] = github_com_nsf_termbox_go.KeyCtrlSlash
Api["github.com/nsf/termbox-go"]["KeyCtrlUnderscore"] = github_com_nsf_termbox_go.KeyCtrlUnderscore
Api["github.com/nsf/termbox-go"]["KeySpace"] = github_com_nsf_termbox_go.KeySpace
Api["github.com/nsf/termbox-go"]["KeyBackspace2"] = github_com_nsf_termbox_go.KeyBackspace2
Api["github.com/nsf/termbox-go"]["KeyCtrl8"] = github_com_nsf_termbox_go.KeyCtrl8
Api["github.com/nsf/termbox-go"]["ModAlt"] = github_com_nsf_termbox_go.ModAlt
Api["github.com/nsf/termbox-go"]["ModMotion"] = github_com_nsf_termbox_go.ModMotion
Api["github.com/nsf/termbox-go"]["OutputCurrent"] = github_com_nsf_termbox_go.OutputCurrent
Api["github.com/nsf/termbox-go"]["OutputNormal"] = github_com_nsf_termbox_go.OutputNormal
Api["github.com/nsf/termbox-go"]["Output256"] = github_com_nsf_termbox_go.Output256
Api["github.com/nsf/termbox-go"]["Output216"] = github_com_nsf_termbox_go.Output216
Api["github.com/nsf/termbox-go"]["OutputGrayscale"] = github_com_nsf_termbox_go.OutputGrayscale
Api["github.com/nsf/termbox-go"]["OutputRGB"] = github_com_nsf_termbox_go.OutputRGB
Api["github.com/nsf/termbox-go"]["SetOutputMode"] = github_com_nsf_termbox_go.SetOutputMode
}
